// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfot-aiZE-PcyCzuOp-bqJxHUvIWfBa-0',
    appId: '1:637910724870:web:6ef1d1ae8354aa08b66e87',
    messagingSenderId: '637910724870',
    projectId: 'grocerylist-b80a3',
    authDomain: 'grocerylist-b80a3.firebaseapp.com',
    storageBucket: 'grocerylist-b80a3.firebasestorage.app',
    measurementId: 'G-71G8TZSG4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwpUC0VeiiwI7jVNVqn7_UWlP0VcCL_c',
    appId: '1:637910724870:android:fea0359315c49d9eb66e87',
    messagingSenderId: '637910724870',
    projectId: 'grocerylist-b80a3',
    storageBucket: 'grocerylist-b80a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKvrQO0Em3LdIy8CjVMPfchztCDYCrwYs',
    appId: '1:637910724870:ios:613e86440fb7eb70b66e87',
    messagingSenderId: '637910724870',
    projectId: 'grocerylist-b80a3',
    storageBucket: 'grocerylist-b80a3.firebasestorage.app',
    iosBundleId: 'com.example.grocerryList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKvrQO0Em3LdIy8CjVMPfchztCDYCrwYs',
    appId: '1:637910724870:ios:613e86440fb7eb70b66e87',
    messagingSenderId: '637910724870',
    projectId: 'grocerylist-b80a3',
    storageBucket: 'grocerylist-b80a3.firebasestorage.app',
    iosBundleId: 'com.example.grocerryList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfot-aiZE-PcyCzuOp-bqJxHUvIWfBa-0',
    appId: '1:637910724870:web:96f17dd3fdaaf8e4b66e87',
    messagingSenderId: '637910724870',
    projectId: 'grocerylist-b80a3',
    authDomain: 'grocerylist-b80a3.firebaseapp.com',
    storageBucket: 'grocerylist-b80a3.firebasestorage.app',
    measurementId: 'G-LSQFL2T7FG',
  );
}
